import { readFile } from "node:fs/promises";
import {
  type Expression,
  type ObjectExpression,
  type Property,
  type Token,
  parseExpressionAt,
  tokTypes,
  tokenizer,
} from "acorn";
import type { Schema } from "../../types.js";
import { isSchema } from "./schema.js";

const ACORN_OPTIONS = {
  ecmaVersion: "latest",
  sourceType: "module",
} as const;

export type SchemaChange =
  | { kind: "database-added"; database: string }
  | { kind: "database-removed"; database: string }
  | {
      kind: "database-id-changed";
      database: string;
      before: string;
      after: string;
    }
  | { kind: "property-added"; database: string; property: string; type: string }
  | {
      kind: "property-removed";
      database: string;
      property: string;
      type: string;
    }
  | {
      kind: "property-type-changed";
      database: string;
      property: string;
      before: string;
      after: string;
    };

/**
 * Read a schema previously generated by the CLI.
 *
 * Acorn is used only for lexical analysis and expression parsing. The
 * resulting AST is converted through a small allowlist; it is never executed.
 * Missing, ambiguous, or manually edited files return null.
 */
export async function readGeneratedSchema(
  schemaPath: string
): Promise<Schema | null> {
  const content = await readFile(schemaPath, "utf8").catch(() => null);
  if (content === null) {
    return null;
  }

  const declarationStart = findSchemaDeclaration(content);
  if (declarationStart === null) {
    return null;
  }

  const parsed = parseSchemaDeclaration(content, declarationStart);
  return isSchema(parsed) ? parsed : null;
}

/**
 * Locate a top-level export declaration with Acorn's tokenizer. Comments and
 * strings are not exposed as identifier tokens. Template literals are treated
 * as unsupported input so interpolation cannot create an ambiguous match.
 */
function findSchemaDeclaration(source: string): number | null {
  try {
    const tokens = Array.from(tokenizer(source, ACORN_OPTIONS));
    const delimiters: Array<"brace" | "paren" | "bracket"> = [];

    for (let index = 0; index < tokens.length; index += 1) {
      const token = tokens[index];
      if (
        token.type === tokTypes.backQuote ||
        token.type === tokTypes.template ||
        token.type === tokTypes.dollarBraceL ||
        token.type === tokTypes.invalidTemplate
      ) {
        return null;
      }

      if (delimiters.length === 0 && token.type === tokTypes._export) {
        const constToken = tokens[index + 1];
        const schemaToken = tokens[index + 2];
        const equalsToken = tokens[index + 3];
        if (
          constToken?.type === tokTypes._const &&
          schemaToken !== undefined &&
          source.slice(schemaToken.start, schemaToken.end) === "schema" &&
          equalsToken !== undefined &&
          source.slice(equalsToken.start, equalsToken.end) === "="
        ) {
          return equalsToken.end;
        }
      }

      if (token.type === tokTypes.braceL) {
        delimiters.push("brace");
      } else if (token.type === tokTypes.parenL) {
        delimiters.push("paren");
      } else if (token.type === tokTypes.bracketL) {
        delimiters.push("bracket");
      } else if (token.type === tokTypes.braceR) {
        if (delimiters.pop() !== "brace") {
          return null;
        }
      } else if (token.type === tokTypes.parenR) {
        if (delimiters.pop() !== "paren") {
          return null;
        }
      } else if (token.type === tokTypes.bracketR) {
        if (delimiters.pop() !== "bracket") {
          return null;
        }
      }
    }
  } catch {
    return null;
  }
  return null;
}

/**
 * Parse only the object expression followed by the generated TS wrapper.
 * Acorn accepts single/double quotes, trailing commas, and Unicode identifiers
 * while keeping arbitrary expressions in the AST for explicit rejection.
 */
function parseSchemaDeclaration(source: string, start: number): unknown {
  try {
    const expression = parseExpressionAt(source, start, ACORN_OPTIONS);
    if (expression.type !== "ObjectExpression") {
      return null;
    }

    const wrapperTokens = Array.from(
      tokenizer(source.slice(expression.end), ACORN_OPTIONS)
    );
    if (
      wrapperTokens.length < 2 ||
      tokenText(source, expression.end, wrapperTokens[0]) !== "satisfies" ||
      tokenText(source, expression.end, wrapperTokens[1]) !== "Schema"
    ) {
      return null;
    }

    if (wrapperTokens.length === 2) {
      return expressionToValue(expression);
    }

    const remainder = wrapperTokens[2];
    const remainderText = tokenText(source, expression.end, remainder);
    if (remainderText === ";") {
      if (wrapperTokens.length === 3) {
        return expressionToValue(expression);
      }
      return hasGeneratedClientWrapper(
        source,
        expression.end,
        wrapperTokens,
        3,
        remainder
      )
        ? expressionToValue(expression)
        : null;
    }

    if (
      remainderText !== "export" ||
      !hasLineBreak(
        source,
        expression.end + wrapperTokens[1].end,
        expression.end + remainder.start
      )
    ) {
      return null;
    }

    return hasGeneratedClientWrapper(
      source,
      expression.end,
      wrapperTokens,
      2,
      wrapperTokens[1]
    )
      ? expressionToValue(expression)
      : null;
  } catch {
    return null;
  }
}

function hasGeneratedClientWrapper(
  source: string,
  offset: number,
  tokens: readonly Token[],
  start: number,
  previous: Token
): boolean {
  if (
    !hasLineBreak(source, offset + previous.end, offset + tokens[start].start)
  ) {
    return false;
  }

  const expected = [
    "export",
    "const",
    "nc",
    "=",
    "new",
    "Client",
    "(",
    "{",
    "schema",
    "}",
    ")",
  ];
  const end = start + expected.length;
  if (tokens.length !== end && tokens.length !== end + 1) {
    return false;
  }

  for (let index = 0; index < expected.length; index += 1) {
    if (tokenText(source, offset, tokens[start + index]) !== expected[index]) {
      return false;
    }
  }

  if (tokens.length === end) {
    return true;
  }

  const afterWrapper = tokens[end];
  return (
    tokenText(source, offset, afterWrapper) === ";" && tokens.length === end + 1
  );
}

function hasLineBreak(source: string, start: number, end: number): boolean {
  return /[\r\n]/u.test(source.slice(start, end));
}

function tokenText(source: string, offset: number, token: Token): string {
  return source.slice(offset + token.start, offset + token.end);
}

function expressionToValue(expression: Expression): unknown {
  if (expression.type === "Literal") {
    if (typeof expression.value !== "string") {
      throw new Error("Schema values must be strings");
    }
    return expression.value;
  }
  if (expression.type !== "ObjectExpression") {
    throw new Error("Schema expressions must be objects or strings");
  }
  return objectToValue(expression);
}

function objectToValue(expression: ObjectExpression): Record<string, unknown> {
  const value = Object.create(null) as Record<string, unknown>;
  for (const property of expression.properties) {
    if (
      property.type !== "Property" ||
      property.kind !== "init" ||
      property.method ||
      property.computed ||
      property.shorthand
    ) {
      throw new Error("Unsupported schema property");
    }

    const key = propertyKey(property);
    if (Object.prototype.hasOwnProperty.call(value, key)) {
      throw new Error("Duplicate schema key");
    }
    value[key] = expressionToValue(property.value);
  }
  return value;
}

function propertyKey(property: Property): string {
  if (property.key.type === "Identifier") {
    return property.key.name;
  }
  if (
    property.key.type === "Literal" &&
    typeof property.key.value === "string"
  ) {
    return property.key.value;
  }
  throw new Error("Schema keys must be identifiers or strings");
}

/**
 * Compare two validated schemas. Database and property names are sorted so
 * output remains stable even when API or object insertion order changes.
 */
export function diffSchemas(previous: Schema, current: Schema): SchemaChange[] {
  const databaseNames = Array.from(
    new Set([...Object.keys(previous), ...Object.keys(current)])
  ).sort();
  const changes: SchemaChange[] = [];

  for (const database of databaseNames) {
    const hasPreviousDatabase = hasOwn(previous, database);
    const hasCurrentDatabase = hasOwn(current, database);

    if (!hasPreviousDatabase) {
      changes.push({ kind: "database-added", database });
      continue;
    }
    if (!hasCurrentDatabase) {
      changes.push({ kind: "database-removed", database });
      continue;
    }

    const before = previous[database];
    const after = current[database];

    if (before.id !== after.id) {
      changes.push({
        kind: "database-id-changed",
        database,
        before: before.id,
        after: after.id,
      });
    }

    const propertyNames = Array.from(
      new Set([
        ...Object.keys(before.properties),
        ...Object.keys(after.properties),
      ])
    ).sort();

    for (const property of propertyNames) {
      const hasPreviousProperty = hasOwn(before.properties, property);
      const hasCurrentProperty = hasOwn(after.properties, property);

      if (!hasPreviousProperty) {
        changes.push({
          kind: "property-added",
          database,
          property,
          type: after.properties[property],
        });
        continue;
      }
      if (!hasCurrentProperty) {
        changes.push({
          kind: "property-removed",
          database,
          property,
          type: before.properties[property],
        });
        continue;
      }
      const beforeType = before.properties[property];
      const afterType = after.properties[property];
      if (beforeType !== afterType) {
        changes.push({
          kind: "property-type-changed",
          database,
          property,
          before: beforeType,
          after: afterType,
        });
      }
    }
  }

  return changes;
}

function hasOwn(object: object, key: PropertyKey): boolean {
  return Object.prototype.hasOwnProperty.call(object, key);
}

export function formatSchemaChanges(
  changes: readonly SchemaChange[] | null
): string {
  if (changes === null) {
    return "No previous generated schema was available for comparison.";
  }
  if (changes.length === 0) {
    return "No schema changes detected.";
  }

  const lines = ["Schema changes:"];
  for (const change of changes) {
    switch (change.kind) {
      case "database-added":
        lines.push(`Added database: ${quote(change.database)}`);
        break;
      case "database-removed":
        lines.push(`Removed database: ${quote(change.database)}`);
        break;
      case "database-id-changed":
        lines.push(`Changed database ID: ${quote(change.database)}`);
        lines.push(`  ${quote(change.before)} -> ${quote(change.after)}`);
        break;
      case "property-added":
        lines.push(
          `Added property: ${propertyLabel(change)} (${quote(change.type)})`
        );
        break;
      case "property-removed":
        lines.push(
          `Removed property: ${propertyLabel(change)} (${quote(change.type)})`
        );
        break;
      case "property-type-changed":
        lines.push(`Changed property type: ${propertyLabel(change)}`);
        lines.push(`  ${quote(change.before)} -> ${quote(change.after)}`);
        break;
    }
  }
  return lines.join("\n");
}

function propertyLabel(change: {
  database: string;
  property: string;
}): string {
  return `${quote(change.database)}.${quote(change.property)}`;
}

function quote(value: string): string {
  return JSON.stringify(value).replace(
    /[\u007f-\u009f\u2028\u2029]/gu,
    (character) => `\\u${character.charCodeAt(0).toString(16).padStart(4, "0")}`
  );
}
