import { EventEmitter } from "node:events";
import { promises as fs, existsSync, writeFileSync } from "node:fs";
import { tmpdir } from "node:os";
import path from "node:path";

const promptMocks = vi.hoisted(() => ({
  confirm: vi.fn(),
}));
const childProcessMocks = vi.hoisted(() => ({
  spawn: vi.fn(),
}));

vi.mock("@inquirer/prompts", () => promptMocks);
vi.mock("node:child_process", () => childProcessMocks);

import { ensureNotcmsDependency } from "../src/cli/features/dependency";

describe("Yarn PnP dependency verification consent boundary", () => {
  let dir: string;
  let initialExecutionMarker: string;
  let postInstallExecutionMarker: string;
  let pnpPath: string;

  beforeEach(async () => {
    dir = await fs.mkdtemp(path.join(tmpdir(), "notcms-pnp-security-"));
    initialExecutionMarker = path.join(dir, "initial-pnp-executed");
    postInstallExecutionMarker = path.join(dir, "post-install-pnp-executed");
    pnpPath = path.join(dir, ".pnp.cjs");
    await fs.writeFile(
      path.join(dir, "package.json"),
      JSON.stringify({
        name: "notcms-pnp-security-fixture",
        packageManager: "yarn@4.9.2",
        dependencies: { notcms: "1.0.0" },
      })
    );
    await writeExecutablePnpFixture(pnpPath, initialExecutionMarker, false);
  });

  afterEach(async () => {
    vi.clearAllMocks();
    await fs.rm(dir, { recursive: true, force: true });
  });

  it("does not execute target PnP code in a non-interactive session", async () => {
    await expect(
      ensureNotcmsDependency({
        cwd: dir,
        interactive: false,
        userAgent: "yarn/4.9.2",
      })
    ).resolves.toEqual({
      status: "manual",
      reason: "non-interactive",
      packageManager: "yarn",
      command: "yarn install",
      verificationRequired: "target-pnp",
    });

    expect(existsSync(initialExecutionMarker)).toBe(false);
    expect(promptMocks.confirm).not.toHaveBeenCalled();
    expect(childProcessMocks.spawn).not.toHaveBeenCalled();
  });

  it("does not execute target PnP code when verification is declined", async () => {
    promptMocks.confirm.mockResolvedValue(false);

    await expect(
      ensureNotcmsDependency({
        cwd: dir,
        interactive: true,
        userAgent: "yarn/4.9.2",
      })
    ).resolves.toEqual(
      expect.objectContaining({
        status: "manual",
        reason: "declined",
        verificationRequired: "target-pnp",
      })
    );

    expect(existsSync(initialExecutionMarker)).toBe(false);
    expect(childProcessMocks.spawn).not.toHaveBeenCalled();
  });

  it("does not execute target PnP code when the approved install fails", async () => {
    promptMocks.confirm.mockResolvedValue(true);
    childProcessMocks.spawn.mockImplementation(() => closingChild(7));

    await expect(
      ensureNotcmsDependency({
        cwd: dir,
        interactive: true,
        userAgent: "yarn/4.9.2",
      })
    ).resolves.toEqual(
      expect.objectContaining({
        status: "manual",
        reason: "failed",
        verificationRequired: "target-pnp",
      })
    );

    expect(existsSync(initialExecutionMarker)).toBe(false);
  });

  it("loads only the fresh target PnP API after an approved install succeeds", async () => {
    promptMocks.confirm.mockResolvedValue(true);
    childProcessMocks.spawn.mockImplementation(() => {
      const child = new EventEmitter();
      queueMicrotask(() => {
        writeExecutablePnpFixtureSync(
          pnpPath,
          postInstallExecutionMarker,
          true
        );
        child.emit("close", 0, null);
      });
      return child;
    });

    await expect(
      ensureNotcmsDependency({
        cwd: dir,
        interactive: true,
        userAgent: "yarn/4.9.2",
      })
    ).resolves.toEqual({
      status: "installed",
      packageManager: "yarn",
      command: "yarn install",
    });

    expect(existsSync(initialExecutionMarker)).toBe(false);
    expect(existsSync(postInstallExecutionMarker)).toBe(true);
  });

  it("verifies a target PnP map first generated by the approved install", async () => {
    await fs.rm(pnpPath);
    promptMocks.confirm.mockResolvedValue(true);
    childProcessMocks.spawn.mockImplementation(() => {
      const child = new EventEmitter();
      queueMicrotask(() => {
        writeExecutablePnpFixtureSync(
          pnpPath,
          postInstallExecutionMarker,
          true
        );
        child.emit("close", 0, null);
      });
      return child;
    });

    await expect(
      ensureNotcmsDependency({
        cwd: dir,
        interactive: true,
        userAgent: "yarn/4.9.2",
      })
    ).resolves.toEqual({
      status: "installed",
      packageManager: "yarn",
      command: "yarn install",
    });

    expect(existsSync(postInstallExecutionMarker)).toBe(true);
    expect(promptMocks.confirm).toHaveBeenCalledWith(
      expect.objectContaining({
        message: expect.stringContaining("declared but not installed"),
      })
    );
  });

  it("redetects a Yarn boundary first generated by the approved add", async () => {
    await fs.rm(pnpPath);
    await fs.writeFile(
      path.join(dir, "package.json"),
      JSON.stringify({
        name: "notcms-fresh-yarn-fixture",
        private: true,
      })
    );
    promptMocks.confirm.mockResolvedValue(true);
    childProcessMocks.spawn.mockImplementation(() => {
      const child = new EventEmitter();
      queueMicrotask(() => {
        writeFileSync(
          path.join(dir, "package.json"),
          JSON.stringify({
            name: "notcms-fresh-yarn-fixture",
            private: true,
            dependencies: { notcms: "1.0.0" },
          })
        );
        writeFileSync(
          path.join(dir, "yarn.lock"),
          "__metadata:\n  version: 8\n"
        );
        writeExecutablePnpFixtureSync(
          pnpPath,
          postInstallExecutionMarker,
          true
        );
        child.emit("close", 0, null);
      });
      return child;
    });

    await expect(
      ensureNotcmsDependency({
        cwd: dir,
        interactive: true,
        userAgent: "yarn/4.9.2",
      })
    ).resolves.toEqual({
      status: "installed",
      packageManager: "yarn",
      command: "yarn add notcms",
    });

    expect(existsSync(postInstallExecutionMarker)).toBe(true);
  });

  it("accepts a safely resolvable direct dependency before parsing stale package-manager metadata", async () => {
    await fs.writeFile(
      path.join(dir, "package.json"),
      JSON.stringify({
        name: "notcms-installed-invalid-manager-fixture",
        packageManager: "yarn; execute-project-code",
        dependencies: { notcms: "1.0.0" },
      })
    );
    const packageDirectory = path.join(dir, "node_modules", "notcms");
    await fs.mkdir(packageDirectory, { recursive: true });
    await fs.writeFile(
      path.join(packageDirectory, "package.json"),
      JSON.stringify({ name: "notcms", main: "index.js" })
    );
    await fs.writeFile(path.join(packageDirectory, "index.js"), "export {};");

    await expect(
      ensureNotcmsDependency({
        cwd: dir,
        interactive: true,
        userAgent: "npm/11.0.0",
      })
    ).resolves.toEqual({ status: "already-installed" });

    expect(existsSync(initialExecutionMarker)).toBe(false);
    expect(promptMocks.confirm).not.toHaveBeenCalled();
    expect(childProcessMocks.spawn).not.toHaveBeenCalled();
  });

  it.each([
    ["npm", "11.0.0"],
    ["pnpm", "10.0.0"],
    ["bun", "1.2.0"],
  ] as const)(
    "does not inspect an ancestor PnP map after an approved %s install",
    async (packageManager, version) => {
      const nestedProject = path.join(dir, packageManager);
      await fs.mkdir(nestedProject);
      await fs.writeFile(
        path.join(nestedProject, "package.json"),
        JSON.stringify({
          name: `notcms-${packageManager}-fixture`,
          packageManager: `${packageManager}@${version}`,
          dependencies: { notcms: "1.0.0" },
        })
      );
      promptMocks.confirm.mockResolvedValue(true);
      childProcessMocks.spawn.mockImplementation(() => closingChild(0));

      await expect(
        ensureNotcmsDependency({
          cwd: nestedProject,
          interactive: true,
          userAgent: `${packageManager}/${version}`,
        })
      ).resolves.toEqual({
        status: "manual",
        reason: "failed",
        packageManager,
        command: `${packageManager} install`,
        error: `${packageManager} install exited successfully, but notcms is still not a direct, resolvable project dependency.`,
      });

      expect(existsSync(initialExecutionMarker)).toBe(false);
      expect(promptMocks.confirm).toHaveBeenCalledWith(
        expect.objectContaining({
          message: expect.not.stringContaining("Yarn PnP"),
        })
      );
    }
  );
});

async function writeExecutablePnpFixture(
  pnpPath: string,
  markerPath: string,
  resolvesNotcms: boolean
) {
  await fs.writeFile(pnpPath, executablePnpFixture(markerPath, resolvesNotcms));
}

function writeExecutablePnpFixtureSync(
  pnpPath: string,
  markerPath: string,
  resolvesNotcms: boolean
) {
  writeFileSync(pnpPath, executablePnpFixture(markerPath, resolvesNotcms));
}

function executablePnpFixture(
  markerPath: string,
  resolvesNotcms: boolean
): string {
  return `require("node:fs").writeFileSync(${JSON.stringify(markerPath)}, "executed");
module.exports = {
  resolveRequest(request) {
    if (request !== "notcms" || ${JSON.stringify(!resolvesNotcms)}) {
      throw new Error("notcms is unresolved");
    }
    return "/virtual/.yarn/cache/notcms.zip/node_modules/notcms/dist/index.js";
  },
};`;
}

function closingChild(exitCode: number) {
  const child = new EventEmitter();
  queueMicrotask(() => child.emit("close", exitCode, null));
  return child;
}
